#!/usr/bin/perl
use strict;
use warnings;
my %dirlist =   ( hd2		=> "ntfs",
		  hd3		=> "ntfs",
		  MACRIUM	=> "vfat",
		  MSIRECOVERY	=> "vfat",
		  RECOVERALL	=> "vfat",
		  MSISOURCES	=> "ntfs",
		  tosh		=> "ntfs",
		  ele		=> "ntfs",
		  myp		=> "ntfs",
		  ad16		=> "vfat",
		  ad64		=> "ext4",
		  trans		=> "ext4",
		  trans16	=> "vfat",
		  ver		=> "vfat",
		  ver8		=> "vfat",
		  axiz		=> "vfat",
		  axiz2		=> "vfat",
		  scd1		=> "vfat",
		  scd2		=> "vfat",
		  sah		=> "vfat",
		  chaos		=> "vfat",
		  tosh8		=> "vfat",
		  xmini		=> "vfat",
		  king		=> "vfat");

# the file fstab to edit
my $fstab = "fstab.bak";

# list for fstab in memory
my @fstab = ();

# open file for reading so the lines with dir in dir list can be deleted
# to prevent multiple inclusions
open (FH, "<", $fstab) or die "Could not open $fstab: $!\n";

# read each line and push it onto a list if it does not contain any directory in the dir list
while (my $line = <FH>) {
	chomp($line);
	# get each line and push if it is not in dirlist
	# set a flag to true if the dir is in dirlist
	my $dirflag = "false";
	foreach my $dir (keys(%dirlist)) {
		if ($line =~ /$dir/) {
			$dirflag = "true";
		}
	}
	# push the line to the fstab list if the dirflag is flase
	push @fstab, $line unless $dirflag eq "true";
}

# close the file
close FH;

# remove the old fstab
unlink $fstab;

# open the file for appending
open FW, ">>", $fstab or die "Could not open $fstab: $!\n";

# write the file with directories from dir list removed
foreach my $line (@fstab) {
	print FW "$line\n";
}

# now append all my custom directory entries to the file
my $ntfsvfatoptions = "noauto,uid=robert,gid=robert,umask=007";
my $ext4options = "defaults,noauto";

foreach my $dir (keys(%dirlist)) {
	# for ntfs
	if ($dirlist{$dir} eq "ntfs") {
		printf FW "%-20s %-20s %-10s %-40s %5s %5s", "LABEL=$dir", "/mnt/$dir", "ntfs", $ntfsvfatoptions, "0", "0\n";
	# for ext4
	} elsif ($dirlist{$dir} eq "ext4") {
		printf FW "%-20s %-20s %-10s %-40s %5s %5s", "LABEL=$dir", "/mnt/$dir", "ext4", $ext4options, "0", "0\n";
	#for vfat
	} elsif ($dirlist{$dir} eq "vfat") {
		printf FW "%-20s %-20s %-10s %-40s %5s %5s", "LABEL=$dir", "/mnt/$dir", "vfat", $ntfsvfatoptions, "0", "0\n";
	}

}
# close the file
close FW;

