#!/bin/bash
# editfstab:prerm
# $1 parameter passed when called
# values are: upgrade, configure, remove or purge

if test "$1" = "remove"; then
	if test -x /usr/local/bin/editfstab; then
		# remove the made directories
		/usr/local/bin/editfstab -r
		# restore fstab
		/usr/local/bin/editfstab -R
	fi
fi
